name: Coverage

on: [ push, pull_request, workflow_dispatch ]

jobs:
  java:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Maven Cache"
        uses: actions/cache@v2
        env:
          cache-name: cache-maven-dependencies
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-cache-maven-${{ hashFiles('**/pom.xml') }}

      - name: "Setup Java"
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: "Maven Build"
        run: mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V

      - name: "Maven Test"
        run: mvn clean test cobertura:cobertura jacoco:report coveralls:report -DdryRun=true

      - name: "Send to Coveralls (build ${{ github.run_number }}-java)"
        uses: MikeEdgar/github-action@raw_coverage_file
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: ${{ github.run_number }}-java
          parallel: false
          path-to-file: './target/coveralls.json'
          coverage-format: raw
